# @package _global_

CKPT: "."

experiment:
  batch_size: 1
  workers: 0
  name: ganimator_experiment

engine:
  runner:
    deterministic: false # required for index add ops
    gpus: [0]
    devices: 1
    num_sanity_val_steps: 0
    max_epochs: 4
    checkpoint:
      monitor: fid/repeated_npz
      mode: min
      filename: "{epoch}-{fid/repeated_npz:.8f}"
      save_weights_only: true
  modules:
    clearml:
      project_name: Ganimator
      task_name: ${experiment.name}
      tags: [test]
    rerun:
      annotations:
        parents:
          mixamo:
            [
              -1,
              0,
              1,
              2,
              3,
              4,
              0,
              6,
              7,
              8,
              9,
              0,
              11,
              12,
              13,
              14,
              13,
              16,
              17,
              18,
              13,
              20,
              21,
              22,
            ]
        labels:
          mixamo:
            - "Hips" # 0
            - "LeftUpLeg" # 1
            - "LeftLeg" # 2
            - "LeftFoot" # 3
            - "LeftToeBase" # 4
            - "LeftToe_End" # 5
            - "RightUpLeg" # 6
            - "RightLeg" # 7
            - "RightFoot" # 8
            - "RightToeBase" # 9
            - "RightToe_End" # 10
            - "Spine" # 11
            - "Spine1" # 12
            - "Spine2" # 13
            - "Neck" # 14
            - "Head" # 15
            - "LeftShoulder" # 16
            - "LeftArm" # 17
            - "LeftForeArm" # 18
            - "LeftHand" # 19
            - "RightShoulder" # 20
            - "RightArm" # 21
            - "RightForeArm" # 22
            - "RightHand" # 23
